name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar_v2: ^5.3.1
  flutter_bloc: ^8.1.6
  persistent_bottom_nav_bar: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_carousel_widget: ^3.1.0
  meta: ^1.15.0
  bloc: ^8.1.4
  flutter_dash: ^1.0.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
